### ISSUE TITLE
Thermal Water not centered, 3x3 square 1x3 falls off 

### ISSUE THREAD

**Issue by Petkip** [h8ul-modder/factorio-ribbon-maze#26] opened 2018-12-06 20:16 UTC
hey, the thermal water from angels ores isn't centering properly, it generates a 3x3 if you cheat to see the maze, but when you get there a 1x3 strip falls off. included some pics of it.

I was using a version from GitHub today 6-12-2018

greetings petkip

![20181206210611_1](https://user-images.githubusercontent.com/38477979/49609204-1efdd980-f99b-11e8-800e-c61c75e2f3be.jpg)
![20181206210619_1](https://user-images.githubusercontent.com/38477979/49609206-1efdd980-f99b-11e8-96ff-dab0316e946a.jpg)
![20181206210328_1](https://user-images.githubusercontent.com/38477979/49609209-1f967000-f99b-11e8-802f-f8fefe5ad15d.jpg)
![20181206210332_1](https://user-images.githubusercontent.com/38477979/49609210-1f967000-f99b-11e8-96a4-fc917665b908.jpg)
![20181206210541_1](https://user-images.githubusercontent.com/38477979/49609211-1f967000-f99b-11e8-87cc-b569051406dd.jpg)
![20181206210546_1](https://user-images.githubusercontent.com/38477979/49609213-1f967000-f99b-11e8-95bb-9676bc7b5511.jpg)

**Comment by OvermindDL1** [comment] 2018-12-06 21:08
The issue is in this function:
https://github.com/h8ul-modder/factorio-ribbon-maze/blob/HEAD/control/settings-control.lua#L219

Specifically the offset is set by doing:
```lua
    local offsetX = math.ceil(-collisionBox.left_top.x)
    local offsetY = math.ceil(-collisionBox.left_top.y)
```
Which is fine if you can get an even number of the things to fill it.

However with fissure's you can't, they have a lot of 'leftover' space.

Thus what needs to be done is either one of:

* Adjust the offset to include half of the amount of the 'leftover' space.
* Add 'more' space in-between each of the resources to 'spread' them out to fill up the leftover space.

Personally I'd opt for spreading out the resources to fill up the space as I think it would both look better and make it easier to work around the resources without just a lot of plain empty space 'around' it.

**Comment by h8ul-modder** [comment] 2018-12-06 22:16
Hello! Thanks for the report.

This is fixed in issue #27 which improves the placement of all resources over 1 tile in size.

**Comment by h8ul-modder** [comment] 2018-12-06 22:22
I should say this is an excellent report and was created just before mine, so although I marked this as duplicate for convenience, it is really the original issue ^_^

**Closed** 2018-12-06 22:22 UTC
Labels: duplicate

**Comment by h8ul-modder** [comment] 2018-12-07 02:14
@OvermindDL1 and @Petkip 0.6.7 is now out. Thank you for trying out the development version, it has been very helpful to get feedback! Now it's out, I would recommend to discard any games played with the github development version; 0.6.7 was a big release and there were a bunch of fixes and migrations prepared throughout. If you really want to keep playing them, I'd at least highly recommend scanning out to a good distance to make sure the maze is intact:

/c game.forces.player.chart(game.player.surface, {{x = -400, y = -4096}, {x = 400, y = 100}})

Thanks again for getting involved 👍 :)
